name: Expo EAS Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn' # Changed to cache Yarn dependencies
          cache-dependency-path: app/yarn.lock # Points to your Yarn lockfile

      - name: Setup EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Ensures deterministic installs for testing

      - name: Build APK (Preview)
        run: eas build --platform android --profile preview --non-interactive
